ministryofjustice/hmpps-ciag-careers-induction-ui

- .circleci/config.yml
👷 Enable preprod and prod builds
> ESWE-579 - Enable preprod and prod

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Add missing env variable.
**Reviewers**
@gary-dutton-moj
> ESWE-600_prepare_for_development

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Add missing env variables.
**Reviewers**
@gary-dutton-moj
> ESWE-600_prepare_for_development_fix_variable

- helm_deploy/hmpps-ciag-careers-induction-ui/values.yaml
- integration_tests/e2e/hopingToGetWork.cy.ts
- integration_tests/pages/hopingToGetWork.ts
- server/constants/contentLookup/hopingToGetWork.ts
- server/constants/contentLookup/index.ts
- server/enums/hopingToGetWorkValue.ts
- server/routes/addressLookup.ts
- server/routes/createPlan/hopingToGetWork/hopingToGetWorkController.test.ts
- server/routes/createPlan/hopingToGetWork/hopingToGetWorkController.ts
- server/routes/createPlan/hopingToGetWork/index.test.ts
- server/routes/createPlan/hopingToGetWork/index.ts
- server/routes/createPlan/hopingToGetWork/validationSchema.test.ts
- server/routes/createPlan/hopingToGetWork/validationSchema.ts
- server/routes/index.ts
- server/views/pages/createPlan/hopingToGetWork/index.njk
- New page
- Integration tests
- Update to values to fix deployment error
> Eswe 592 hoping to get work page

- .circleci/config.yml
👷 Change alerts and releases channels
> ESWE-648 - Alerts and releases

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
🚀 Updated and standardised ingress
> ESWE-649 - Certificates

- server/routes/createPlan/abilityToWork/abilityToWorkController.test.ts
- server/routes/createPlan/additionalTraining/additionalTrainingController.test.ts
- server/routes/createPlan/additionalTraining/additionalTrainingController.ts
- server/routes/createPlan/educationLevel/educationLevelController.test.ts
- server/routes/createPlan/educationLevel/educationLevelController.ts
- server/routes/createPlan/inPrisonEducation/inPrisonEducationController.test.ts
- server/routes/createPlan/inPrisonEducation/inPrisonEducationController.ts
- server/routes/createPlan/inPrisonWork/inPrisonWorkController.test.ts
- server/routes/createPlan/particularJobInterests/particularJobInterestsController.test.ts
- server/routes/createPlan/personalInterests/personalInterestsController.test.ts
- server/routes/createPlan/qualifications/qualificationsController.test.ts
- server/routes/createPlan/qualifications/qualificationsController.ts
- server/routes/createPlan/reasonToNotGetWork/reasonToNotGetWorkController.test.ts
- server/routes/createPlan/skills/skillsController.test.ts
- server/routes/createPlan/workDetails/workDetailsController.test.ts
- server/routes/createPlan/workInterests/workInterestsController.test.ts
- server/utils/getHubPageByMode.ts
Fixed back location for education pages, update functionality
> Fix education change back location

- server/routes/createPlan/abilityToWork/abilityToWorkController.ts
- server/routes/createPlan/additionalTraining/additionalTrainingController.ts
- server/routes/createPlan/educationLevel/educationLevelController.ts
- server/routes/createPlan/hasWorkedBefore/hasWorkedBeforeController.ts
- server/routes/createPlan/hopingToGetWork/hopingToGetWorkController.ts
- server/routes/createPlan/inPrisonEducation/inPrisonEducationController.ts
- server/routes/createPlan/inPrisonWork/inPrisonWorkController.ts
- server/routes/createPlan/particularJobInterests/particularJobInterestsController.ts
- server/routes/createPlan/personalInterests/personalInterestsController.ts
- server/routes/createPlan/qualificationDetails/qualificationDetailsController.ts
- server/routes/createPlan/qualifications/qualificationsController.ts
- server/routes/createPlan/reasonToNotGetWork/reasonToNotGetWorkController.ts
- server/routes/createPlan/skills/skillsController.ts
- server/routes/createPlan/typeOfWorkExperience/typeOfWorkExperienceController.ts
- server/routes/createPlan/workDetails/workDetailsController.ts
- server/routes/createPlan/workInterests/workInterestsController.ts
- Fix issue where update does change prisonId if it has changed
> ESWE-740_prisonId_update_issue changed update to always save prisonId

- server/config.ts
- server/utils/urlParameterEncryption.ts
Include passphrase in config
Passphrase added to secret in dev, preprod and prod
> ESWE-741 - Passphrase

- server/data/prisonerSearch/utils.ts
- server/routes/createPlan/hasWorkedBefore/hasWorkedBeforeController.ts
- server/routes/createPlan/hopingToGetWork/hopingToGetWorkController.ts
- server/utils/utils.ts
- server/viewModels/ciagListViewModel.ts
- Fix no to not sure change
- Fix boolean default value issue causing a few issues
- Fix status filter
> ESWE-744 bug fixes

- integration_tests/e2e/abilityToWork.cy.ts
- integration_tests/e2e/additionalTraining.cy.ts
- integration_tests/e2e/checkYourAnswersFull.cy.ts
- integration_tests/e2e/checkYourAnswersLite.cy.ts
- integration_tests/e2e/educationLevel.cy.ts
- integration_tests/e2e/hasWorkedBefore.cy.ts
- integration_tests/e2e/inPrisonEducation.cy.ts
- integration_tests/e2e/inPrisonWork.cy.ts
- integration_tests/e2e/jobDetails.cy.ts
- integration_tests/e2e/particularJobInterests.cy.ts
- integration_tests/e2e/personalInterests.cy.ts
- integration_tests/e2e/qualificationDetails.cy.ts
- integration_tests/e2e/qualificationLevel.cy.ts
- integration_tests/e2e/reasonToNotGetWork.cy.ts
- integration_tests/e2e/skills.cy.ts
- integration_tests/e2e/typeOfWorkExperience.cy.ts
- integration_tests/e2e/wantsToAddQualifications.cy.ts
- integration_tests/e2e/workInterests.cy.ts
- server/routes/createPlan/particularJobInterests/particularJobInterestsController.ts
- server/routes/createPlan/wantsToAddQualifications/wantsToAddQualificationsController.test.ts
- server/utils/pageTitleLookup.ts
- server/views/pages/createPlan/checkYourAnswers/partials/_educationAndTraining.njk
- server/views/pages/createPlan/checkYourAnswers/partials/_skillsAndInterests.njk
- server/views/pages/createPlan/checkYourAnswers/partials/_workOnRelease.njk
- server/views/pages/createPlan/educationLevel/index.njk
- server/views/pages/createPlan/reasonToNotGetWork/index.njk
- Change the level of education content
- Change reason for not hoping to work content
> Eswe 742 assorted content changes

- junit.xml
- server/data/educationAndWorkPlanApi/educationAndWorkPlanApi.test.ts
- server/routes/ciagList/validationSchema.test.ts
- server/services/ciagService.test.ts
- server/services/curiousEsweService.test.ts
Additional unit tests.
**Reviewers**
@gary-dutton-moj
> ESWE-575_CIAG_Handover_UI_Unit_test_coverage

- .circleci/config.yml
- helm_deploy/hmpps-ciag-careers-induction-ui/Chart.yaml
- helm_deploy/hmpps-ciag-careers-induction-ui/values.yaml
- helm_deploy/values-dev.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
2 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal,prisons,private_prisons`
- The size of the allowlist defined in this file will change: `87 => 5 (82 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
The following IPs have been identified as unnecessary and will be removed by applying this PR:
- …
> Migrating project to use groups in allowlist

- helm_deploy/hmpps-ciag-careers-induction-ui/Chart.yaml
Upgrade generic-service to latest
Upgrade generic-prometheus-alerts to latest
Bump version
> ESWE-752 - Upgrade Helm Charts 

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
PR to switch over to the PLP version of the CIAG API in all envs.
> RR-516 - Switch over to PLP version of CIAG API

- README.md
- server/config.ts
- server/middleware/plpFrontendRedirect.test.ts
- server/middleware/plpFrontendRedirect.ts
- server/routes/addressLookup.ts
- server/routes/ciagList/ciagListController.test.ts
- server/routes/ciagList/index.test.ts
- server/routes/ciagList/index.ts
- server/routes/workPlan/index.test.ts
- server/routes/workPlan/index.ts
- server/views/pages/ciagList/partials/_searchBox.njk
- Added feature flag for PLP page redirects
- Added logic changes
- Rename prisonerSearch address to ciagList in address lookup
> Eswe 753 feature flagged homepage change

- helm_deploy/values-prod.yaml
> BUGFIX - Web Timeout

- helm_deploy/hmpps-ciag-careers-induction-ui/values.yaml
Add the farsight-devs GH team to the modsec rules config so we can see the errors in the logs
> RR-538 - Add the farsight-devs GH team to the modsec rules config

- helm_deploy/values-dev.yaml
This PR handles modsec false positives for rule 942440 **in dev only**. I am not proposing this goes anywhere near `prod` this close to the code freeze, but we can test it in `dev` in the run up to Xmas and NY
For reference, these are the relevant modsec logs that we are trying to mitigate with this change:
```
{
"message": "SQL Comment Sequence Detected",
"details": {
"match": "Matched \"Operator `Rx' with parameter `(?:/\\*!?|\\*/|[';]--|--[\\s\\r\\n\\v\\f]|--[^-]*?-|[^&-]#.*?[\\s\\r\\n\\v\\f]|;?\\\\x00)' against variable `REQUEST_COOKIES:connect.sid' (Value: `s%3Ad93u8slJqP--lEjvuXCKRAz2AXWIXVR-.kIFH5gtR3R51gmWcWWlpx6KYYbtnvjFMb1HwF8g4U1s' )",
"reference": "o12,22v1120,80t:urlDecodeUni",
"ruleId": "942440",
"file": "/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-S …
```
> RR-538 - Handle modsec false positives for rule 942440

- helm_deploy/hmpps-ciag-careers-induction-ui/values.yaml
Change the redis cache secret name to that of the namespace that we now deploy to (PLP namespace)
> RR-573 - Change the redis cache secret name to that of the namespace that we now deploy to (PLP namespace)

- helm_deploy/values-prod.yaml
Use the correct URL for `CURIOUS_API_URL`
> Use the correct URL for CURIOUS_API_URL

- integration_tests/e2e/checkYourAnswersFull.cy.ts
- integration_tests/e2e/updateInduction.cy.ts
- integration_tests/mockApis/educationAndWorkPlanApi.ts
- integration_tests/mockApis/wiremock.ts
- integration_tests/mockData/prisonerByIdData.ts
- integration_tests/tsconfig.json
This PR ensures that we are calling wiremock with expected values when creating or updating an Induction.
> RR-628 - Wiremock verifications for create/update Induction

- server/views/pages/createPlan/qualifications/partials/_assessments.njk
- server/views/pages/createPlan/wantsToAddQualifications/partials/_assessments.njk
Update the functional skills content
https://dsdmoj.atlassian.net/jira/software/c/projects/RR/boards/1214
> RR-625 functional skills content changes

- server/routes/createPlan/additionalTraining/additionalTrainingController.test.ts
- server/routes/createPlan/additionalTraining/additionalTrainingController.ts
- server/routes/createPlan/additionalTraining/index.ts
- server/routes/createPlan/educationLevel/educationLevelController.test.ts
- server/routes/createPlan/educationLevel/educationLevelController.ts
- server/routes/createPlan/educationLevel/index.ts
- server/routes/createPlan/hasWorkedBefore/hasWorkedBeforeController.test.ts
- server/routes/createPlan/hasWorkedBefore/hasWorkedBeforeController.ts
- server/routes/createPlan/hasWorkedBefore/index.ts
- server/routes/createPlan/hopingToGetWork/hopingToGetWorkController.test.ts
- server/routes/createPlan/hopingToGetWork/hopingToGetWorkController.ts
- server/routes/createPlan/hopingToGetWork/index.ts
The second in a series of PRs following my previous one https://github.com/ministryofjustice/hmpps-ciag-careers-induction-ui/pull/139
> RR-631 - Use new Inductions API (Additional Training to Hoping to Get Work)

- server/routes/createPlan/typeOfWorkExperience/index.ts
- server/routes/createPlan/typeOfWorkExperience/typeOfWorkExperienceController.test.ts
- server/routes/createPlan/typeOfWorkExperience/typeOfWorkExperienceController.ts
- server/routes/createPlan/workDetails/index.ts
- server/routes/createPlan/workDetails/workDetailsController.test.ts
- server/routes/createPlan/workDetails/workDetailsController.ts
- server/routes/createPlan/workInterests/index.ts
- server/routes/createPlan/workInterests/workInterestsController.test.ts
- server/routes/createPlan/workInterests/workInterestsController.ts
The third in the series of PRs based on #139
> RR-631 - Use new Inductions API (Type of Work Experience to Work Interests)

- server/routes/createPlan/abilityToWork/abilityToWorkController.test.ts
- server/routes/createPlan/additionalTraining/additionalTrainingController.test.ts
- server/routes/createPlan/hasWorkedBefore/hasWorkedBeforeController.test.ts
- server/routes/createPlan/hopingToGetWork/hopingToGetWorkController.test.ts
- server/routes/createPlan/inPrisonEducation/inPrisonEducationController.test.ts
- server/routes/createPlan/inPrisonEducation/inPrisonEducationController.ts
- server/routes/createPlan/inPrisonEducation/index.ts
- server/routes/createPlan/inPrisonWork/inPrisonWorkController.test.ts
- server/routes/createPlan/inPrisonWork/inPrisonWorkController.ts
- server/routes/createPlan/inPrisonWork/index.ts
- server/routes/createPlan/particularJobInterests/index.ts
- server/routes/createPlan/particularJobInterests/particularJobInterestsController.test.ts
- server/routes/createPlan/particularJobInterests/particularJobInterestsController.ts
- server/routes/createPlan/personalInterests/index.ts
- server/routes/createPlan/personalInterests/personalInterestsController.test.ts
- server/routes/createPlan/personalInterests/personalInterestsController.ts
Another PR in the series of calling the new Inductions API.
> RR-631 - Use new Inductions API (In Prison Training to Personal Interests)

- server/routes/createPlan/qualifications/index.ts
- server/routes/createPlan/qualifications/qualificationsController.test.ts
- server/routes/createPlan/qualifications/qualificationsController.ts
- server/routes/createPlan/reasonToNotGetWork/index.ts
- server/routes/createPlan/reasonToNotGetWork/reasonToNotGetWorkController.test.ts
- server/routes/createPlan/reasonToNotGetWork/reasonToNotGetWorkController.ts
- server/routes/createPlan/skills/index.ts
- server/routes/createPlan/skills/skillsController.test.ts
- server/routes/createPlan/skills/skillsController.ts
Another PR in the series of calling the new Inductions API.
> RR-631 - Use new Inductions API (Qualifications to Skills)

- server/routes/createPlan/qualificationDetails/index.ts
- server/routes/createPlan/qualificationDetails/qualificationDetailsController.test.ts
- server/routes/createPlan/qualificationDetails/qualificationDetailsController.ts
The last in a series of PRs to call the new Update Induction endpoint
> RR-631 - Use new Inductions API - Qualification Details

- server/views/pages/createPlan/qualifications/partials/_assessments.njk
- server/views/pages/createPlan/wantsToAddQualifications/partials/_assessments.njk
Content change to functional skills headers
https://dsdmoj.atlassian.net/browse/RR-625
> RR-625 content change to functional skills headers

- helm_deploy/hmpps-ciag-careers-induction-ui/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
Enables the feature toggle in prod to use the new Induction API (rather than the CIAG API)
> RR-518 - Enable feature toggle in prod
